version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile.dev
    environment:
      APP_HTTP_PORT: 8000

      APP_MONGO_URL: mongodb://admin:admin@mongo

      APP_RABBITMQ_URL: amqp://admin:admin@rabbitmq/default
      APP_RABBITMQ_EXCHANGE_NAME: trading
    ports:
      - 8000:8000
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - ./cmd:/app/cmd
      - ./pkg:/app/pkg
      - ./main.go:/app/main.go

  mongo:
   image: mongo:4.4
   restart: always
   environment:
     MONGO_INITDB_ROOT_USERNAME: admin
     MONGO_INITDB_ROOT_PASSWORD: admin
   ports:
     - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: default
    ports:
      - 15672:15672
